---
apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: infisical
  namespace: eso
spec:
  provider:
    infisical:
      auth:
        universalAuthCredentials:
          clientId:
            name: infisical-auth
            namespace: eso
            key: clientId
          clientSecret:
            name: infisical-auth
            namespace: eso
            key: clientSecret
      secretsScope:
        projectSlug: home-kubernetes-d-xhf
        environmentSlug: main
        recursive: true
