---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: velero-credentials
  namespace: velero
  annotations:
    argocd.argoproj.io/sync-wave: '-1'
spec:
  refreshInterval: 1m
  secretStoreRef:
    name: infisical
    kind: ClusterSecretStore
  target:
    name: velero-credentials
    creationPolicy: Owner
    deletionPolicy: Retain
    template:
      data:
        # Velero AWS plugin expects the credentials file under key 'cloud'
        cloud: |
          [default]
          aws_access_key_id={{ .AWS_ACCESS_KEY_ID }}
          aws_secret_access_key={{ .AWS_SECRET_ACCESS_KEY }}
  dataFrom:
    - find:
        conversionStrategy: Default
        decodingStrategy: None
        nullBytePolicy: Ignore
        path: /velero
        name:
          regexp: .*
