---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: psql-admin-credentials
  namespace: psql
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: infisical
    kind: ClusterSecretStore
  target:
    name: psql-admin-credentials
    creationPolicy: Owner
  data:
    - secretKey: postgres-password
      remoteRef:
        key: /psql/ADMIN_PASSWORD
