---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: psql-vvn-ce-credentials
  namespace: psql
  annotations:
    argocd.argoproj.io/sync-wave: '-1'
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: infisical
    kind: ClusterSecretStore
  target:
    name: psql-vvn-ce-credentials
    creationPolicy: Owner
  dataFrom:
    - find:
        path: /psql/vvn-ce
        name:
          regexp: .*
