---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: vvn-backend-secrets
  namespace: vvn
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: infisical
    kind: ClusterSecretStore
  target:
    name: vvn-backend-secrets
    creationPolicy: Owner
  data:
    - secretKey: DATABASE_URL
      remoteRef:
        key: /vvn-ce/DATABASE_URL
    - secretKey: OPENROUTER_API_KEY
      remoteRef:
        key: /vvn-ce/OPENROUTER_API_KEY
