---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: vdict-crawler-secrets
  namespace: vvn
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: infisical
    kind: ClusterSecretStore
  target:
    # Secret name matches what cronjob.yaml references
    name: vdict-crawler-secret
    creationPolicy: Owner
  data:
    - secretKey: db_url
      remoteRef:
        key: /vvn-ce/CRAWLER_DB_URL
