# ---
# apiVersion: external-secrets.io/v1
# kind: ExternalSecret
# metadata:
#   name: postgresql-secrets
#   namespace: vvn
# spec:
#   refreshInterval: 1m
#   secretStoreRef:
#     name: infisical
#     kind: ClusterSecretStore
#   target:
#     name: postgresql-secrets
#     creationPolicy: Owner
#   data:
#     - secretKey: password
#       remoteRef:
#         key: /vvn-ce/POSTGRES_PASSWORD
