---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: hermes-creds
  namespace: hermes
  annotations:
    argocd.argoproj.io/sync-wave: '-1'
spec:
  refreshInterval: 1m
  secretStoreRef:
    name: infisical
    kind: ClusterSecretStore
  target:
    name: hermes-creds
    creationPolicy: Owner
    deletionPolicy: Retain
  dataFrom:
    - find:
        conversionStrategy: Default
        decodingStrategy: None
        nullBytePolicy: Ignore
        path: /hermes
        name:
          regexp: .*
