---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: hermes-http-redirect
  namespace: hermes
spec:
  parentRefs:
    - name: external
      namespace: infra
      sectionName: http
  hostnames: [hermes.qtlab.dev]
  rules:
    - filters:
        - type: RequestRedirect
          requestRedirect:
            scheme: https
            statusCode: 301
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: hermes
  namespace: hermes
spec:
  parentRefs:
    - name: external
      namespace: infra
      sectionName: https
  hostnames: [hermes.qtlab.dev]
  rules:
    - backendRefs:
        - name: hermes
          port: 9119
