---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: multica-daemon-creds
  namespace: hermes
spec:
  refreshInterval: 1m
  secretStoreRef:
    name: infisical
    kind: ClusterSecretStore
  target:
    name: multica-daemon-creds
    creationPolicy: Owner
    deletionPolicy: Retain
  data:
    - secretKey: MULTICA_TOKEN
      remoteRef:
        key: /hermes/MULTICA_TOKEN
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
        nullBytePolicy: Ignore
