---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: ddns-creds
  namespace: ddns
spec:
  refreshInterval: 1m
  secretStoreRef:
    name: infisical
    kind: ClusterSecretStore
  target:
    name: ddns-creds
    creationPolicy: Owner
    deletionPolicy: Retain
  dataFrom:
    - find:
        conversionStrategy: Default
        decodingStrategy: None
        nullBytePolicy: Ignore
        path: /ddns
        name:
          regexp: .*
