---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: psql-admin
  namespace: psql
spec:
  refreshInterval: 1m
  secretStoreRef:
    name: infisical
    kind: ClusterSecretStore
  target:
    name: psql-admin
    creationPolicy: Owner
  data:
    - secretKey: postgres-password  # checkov:skip=CKV_SECRET_6:False positive — this is an Infisical path reference, not an encoded secret value
      remoteRef:
        key: /psql/ADMIN_PASSWORD
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
        nullBytePolicy: Ignore
