---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: vvn-ce-psql
  namespace: vvn-ce
spec:
  refreshInterval: 1m
  secretStoreRef:
    name: infisical
    kind: ClusterSecretStore
  target:
    name: vvn-ce-psql
    creationPolicy: Owner
  dataFrom:
    - find:
        conversionStrategy: Default
        decodingStrategy: None
        nullBytePolicy: Ignore
        path: /psql/vvn-ce
        name:
          regexp: .*
