---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: cloudflare-ddns-secret
  namespace: cloudflare-ddns
  annotations:
    argocd.argoproj.io/sync-wave: '-1'
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: infisical
    kind: ClusterSecretStore
  target:
    name: cloudflare-ddns-secret
    creationPolicy: Owner
    deletionPolicy: Retain
  data:
    - secretKey: CLOUDFLARE_API_TOKEN  # checkov:skip=CKV_SECRET_6:False positive — this is an Infisical path reference, not an encoded secret value
      remoteRef:
        key: /cloudflare-ddns/CLOUDFLARE_API_TOKEN
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
        nullBytePolicy: Ignore
