---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: cloudflare-ddns-secret
  namespace: cloudflare-ddns
  annotations:
    argocd.argoproj.io/sync-wave: '-1'
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: infisical
    kind: ClusterSecretStore
  target:
    name: cloudflare-ddns-secret
    creationPolicy: Owner
    deletionPolicy: Retain
  dataFrom:
    - find:
        path: /cloudflare-ddns
        name:
          regexp: .*
