---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: psql
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: '2'
spec:
  project: default
  sources:
    - chart: postgresql
      repoURL: https://charts.bitnami.com/bitnami
      targetRevision: 18.7.2
      helm:
        releaseName: psql
        values: |
          auth:
            existingSecret: psql-admin
            secretKeys:
              adminPasswordKey: postgres-password
          primary:
            persistentVolumeClaimRetentionPolicy:
              enabled: true
              whenDeleted: Delete
              whenScaled: Retain
    - repoURL: https://github.com/quniv/home-argocd.git
      targetRevision: HEAD
      path: charts/psql-init
      helm:
        releaseName: vvn-ce
        values: |
          secretName: vvn-ce-psql
          dbSecretInfisicalPath: /psql/vvn-ce
          reflectionTargetNamespaces: vvn-ce
  destination:
    server: https://kubernetes.default.svc
    namespace: psql
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions: [CreateNamespace=true]
