---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vvn-ce-backend
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: '2'
spec:
  project: default
  source:
    repoURL: https://github.com/quniv/home-argocd.git
    targetRevision: HEAD
    path: charts/webapp
    helm:
      releaseName: vvn-backend
      valueFiles: [values/vvn-ce.yaml]
  destination:
    server: https://kubernetes.default.svc
    namespace: vvn
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions: [CreateNamespace=true]
