---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: psql-{{ include "psql-init.fullname" . }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "psql-init.labels" . | nindent 4 }}
  annotations:
    argocd.argoproj.io/sync-wave: '-1'
spec:
  refreshInterval: 1m
  secretStoreRef:
    name: {{ .Values.infisical.store }}
    kind: {{ .Values.infisical.storeKind }}
  target:
    name: {{ .Values.secretName }}
    creationPolicy: Owner
  dataFrom:
    - find:
        conversionStrategy: Default
        decodingStrategy: None
        nullBytePolicy: Ignore
        path: {{ .Values.infisical.path }}
        name:
          regexp: .*
