{{- if .Values.dbSecretInfisicalPath }}
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ .Values.secretName }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "psql-init.labels" . | nindent 4 }}
spec:
  refreshInterval: 1m
  secretStoreRef:
    name: infisical
    kind: ClusterSecretStore
  target:
    name: {{ .Values.secretName }}
    creationPolicy: Owner
    {{- with .Values.reflectionTargetNamespaces }}
    template:
      metadata:
        annotations:
          reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
          reflector.v1.k8s.emberstack.com/reflection-allowed-namespaces: {{ . | quote }}
          reflector.v1.k8s.emberstack.com/reflection-auto-enabled: "true"
          reflector.v1.k8s.emberstack.com/reflection-auto-namespaces: {{ . | quote }}
    {{- end }}
  data:
    - secretKey: DB_USER
      remoteRef:
        key: {{ printf "%s/DB_USER" (trimSuffix "/" .Values.dbSecretInfisicalPath) }}
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
        nullBytePolicy: Ignore
    - secretKey: DB_PASSWORD
      remoteRef:
        key: {{ printf "%s/DB_PASSWORD" (trimSuffix "/" .Values.dbSecretInfisicalPath) }}
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
        nullBytePolicy: Ignore
    - secretKey: DB_NAME
      remoteRef:
        key: {{ printf "%s/DB_NAME" (trimSuffix "/" .Values.dbSecretInfisicalPath) }}
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
        nullBytePolicy: Ignore
{{- end }}
