{{- if .Values.dbSecretInfisicalPath }}
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ .Values.secretName }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "psql-init.labels" . | nindent 4 }}
spec:
  refreshInterval: 1m
  secretStoreRef:
    name: infisical
    kind: ClusterSecretStore
  target:
    name: {{ .Values.secretName }}
    creationPolicy: Owner
    {{- with .Values.reflectionTargetNamespaces }}
    template:
      metadata:
        annotations:
          reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
          reflector.v1.k8s.emberstack.com/reflection-allowed-namespaces: {{ . | quote }}
          reflector.v1.k8s.emberstack.com/reflection-auto-enabled: "true"
          reflector.v1.k8s.emberstack.com/reflection-auto-namespaces: {{ . | quote }}
    {{- end }}
  dataFrom:
    - find:
        conversionStrategy: Default
        decodingStrategy: None
        nullBytePolicy: Ignore
        path: {{ .Values.dbSecretInfisicalPath }}
        name:
          regexp: .*
{{- end }}
