{{- if .Values.externalsecret.enabled }}
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ include "webapp.fullname" . }}-secrets
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "webapp.labels" . | nindent 4 }}
spec:
  refreshInterval: {{ .Values.externalsecret.refreshInterval }}
  secretStoreRef:
    name: {{ .Values.externalsecret.store }}
    kind: {{ .Values.externalsecret.storeKind }}
  target:
    name: {{ .Values.externalsecret.targetSecret }}
    creationPolicy: Owner
  data:
    {{- toYaml .Values.externalsecret.data | nindent 4 }}
{{- end }}
